### ISSUE TITLE
GPU-Aware MPI Version

### ISSUE THREAD

**Issue by kabicm** [eth-cscs/COSMA#108]
_Originally posted by @alazzaro in https://github.com/eth-cscs/COSMA/issues/102#issuecomment-1175155215_
@kabicm I did a test with the new COSMA and I can confirm that I get some quite nice speed-up with the G2G MPI option enabled for the CP2K RPA benchmark. Note that I'm using (my default setting to run the benchmark):

```
    export COSMA_GPU_MAX_TILE_M=30000
    export COSMA_GPU_MAX_TILE_N=30000
    export COSMA_GPU_MAX_TILE_K=30000

    export COSMA_CPU_MEMORY_ALIGNMENT=256

    export COSMA_DIM_THRESHOLD=10000 # force only RPA calls to run via COSMA
```

Now, I tried to relax some of the variables. 
If I remove the last variable, so all pdgemm's (including small ones) will go to COSMA, I get an error:

```
Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

gdb) where
#0  0x00007f13e759345d in cosma::Interval::locate_in_subinterval (this=0x7ffd99185980, divisor=1072693248, elem=28) at /home/users/alazzaro/cp2k/libs/COSMA-marko/src/cosma/interval.cpp:66
#1  0x00007f13e7600c17 in cosma::gpu::gpu_aware_mpi_copy<double> (ctx=0x1b62d270, P=..., in=0x1bf44500, out=0x1c0a8500, reshuffle_buffer=0x0, size_before=..., total_before=..., total_after=58368, step=1) at /home/users/alazzaro/cp2k/libs/COSMA-marko/src/cosma/gpu/gpu_aware_mpi_utils.cpp:28
#2  0x00007f13e75c260f in cosma::parallel<double> (ctx=0x1b62d270, matrixA=..., matrixB=..., matrixC=..., m=..., n=..., k=..., P=..., step=1, strategy=..., comm=0x1b2276f0, alpha=1, beta=0) at /home/users/alazzaro/cp2k/libs/COSMA-marko/src/cosma/multiply.cpp:776
#3  0x00007f13e75bf88c in cosma::multiply<double> (ctx=0x1b62d270, matrixA=..., matrixB=..., matrixC=..., m=..., n=..., k=..., P=..., step=1, strategy=..., comm=0x1b2276f0, alpha=1, beta=0) at /home/users/alazzaro/cp2k/libs/COSMA-marko/src/cosma/multiply.cpp:411
#4  0x00007f13e75c26e3 in cosma::parallel<double> (ctx=0x1b62d270, matrixA=..., matrixB=..., matrixC=..., m=..., n=..., k=..., P=..., step=0, strategy=..., comm=0x1b2276f0, alpha=1, beta=0) at /home/users/alazzaro/cp2k/libs/COSMA-marko/src/cosma/multiply.cpp:881
#5  0x00007f13e75bf88c in cosma::multiply<double> (ctx=0x1b62d270, matrixA=..., matrixB=..., matrixC=..., m=..., n=..., k=..., P=..., step=0, strategy=..., comm=0x1b2276f0, alpha=1, beta=0) at /home/users/alazzaro/cp2k/libs/COSMA-marko/src/cosma/multiply.cpp:411
#6  0x00007f13e75bc537 in cosma::multiply<double> (ctx=0x1b62d270, matrixA=..., matrixB=..., matrixC=..., strategy=..., comm=-1006632895, alpha=1, beta=0) at /home/users/alazzaro/cp2k/libs/COSMA-marko/src/cosma/multiply.cpp:283
#7  0x00007f13e75bcde5 in cosma::multiply<double> (matrixA=..., matrixB=..., matrixC=..., strategy=..., comm=-1006632895, alpha=1, beta=0) at /home/users/alazzaro/cp2k/libs/COSMA-marko/src/cosma/multiply.cpp:228
#8  0x00007f13e788736e in cosma::pxgemm<double> (transa=84 'T', transb=78 'N', m=512, n=512, k=7296, alpha=1, a=0x20139060, ia=1, ja=1, desca=0x16e9df50, b=0x20139060, ib=1, jb=1, descb=0x16e9df50, beta=0, c=0x1d8faa90, ic=1, jc=1, descc=0x200f47a0)
    at /home/users/alazzaro/cp2k/libs/COSMA-marko/src/cosma/cosma_pxgemm.cpp:350

```

I assume the problem is that there is a reshuffling of the operations for small multiplications (a small number of ranks involved?)
Maybe you may want to investigate more, let me know if you need more info.

I will also run some more tests at scale (in ~ a month timescale). Thanks!

_Originally posted by @alazzaro in https://github.com/eth-cscs/COSMA/issues/102#issuecomment-1175155215_

**Comment by kabicm** [comment]
@alazzaro Can you try with the latest master commit? Also the submodules are updated.

**Comment by alazzaro** [comment]
Yeap, this problem is fixed now. Thanks!
